- name: copy fabio.hcl file
  template:
    src: ./templates/fabio.hcl.j2
    dest: ~/fabio.hcl

- name: run fabio job
  command: nomad run ~/fabio.hcl

- name: install java 11
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: download jenkins war
  get_url:
    url: https://get.jenkins.io/war-stable/2.303.2/jenkins.war
    dest: /home/vagrant

- name: copy jenkins.service file
  template:
    src: ./templates/jenkins.service.j2
    dest: /usr/lib/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 644

- name: start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: wait until jenkins is up
  uri:
    url: "http://localhost:8080/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
  
- name: get init password jenkins
  shell: cat /root/.jenkins/secrets/initialAdminPassword
  changed_when: false
  register: password

- name: print init password jenkins
  debug:
    var: password.stdout