- hosts: cluster_servers
  become: true
  roles:
    - unzip
    - consul
    - nomad

- hosts: cluster_clients
  become: true
  roles: 
    - unzip
    - docker
    - consul
    - nomad

- hosts: cluster_gw
  become: true
  roles: 
    - docker
    - openldap
    - authz-server
    - envoy

- hosts: server-1
  become: true
  roles: 
    - fabio
    - http-echo