- hosts: all
  become: true
  order: sorted
  serial: 1
  roles:
    - unzip
    - docker
    - consul
    - nomad

- hosts: node-01
  become: true
  roles:
    - health-checker
    - fabio
    - prometheus
    - autoscaler
    - http-echo
    - openldap
    - authz-server
    - envoy
